# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from test_coingecko_python.models.supported_networks_data_inner_attributes import SupportedNetworksDataInnerAttributes

class TestSupportedNetworksDataInnerAttributes(unittest.TestCase):
    """SupportedNetworksDataInnerAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SupportedNetworksDataInnerAttributes:
        """Test SupportedNetworksDataInnerAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SupportedNetworksDataInnerAttributes`
        """
        model = SupportedNetworksDataInnerAttributes()
        if include_optional:
            return SupportedNetworksDataInnerAttributes(
                name = '',
                coingecko_asset_platform_id = ''
            )
        else:
            return SupportedNetworksDataInnerAttributes(
        )
        """

    def testSupportedNetworksDataInnerAttributes(self):
        """Test SupportedNetworksDataInnerAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
