# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from test_coingecko_python.models.supported_networks import SupportedNetworks

class TestSupportedNetworks(unittest.TestCase):
    """SupportedNetworks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SupportedNetworks:
        """Test SupportedNetworks
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SupportedNetworks`
        """
        model = SupportedNetworks()
        if include_optional:
            return SupportedNetworks(
                data = [
                    test_coingecko_python.models.supported_networks_data_inner.SupportedNetworks_data_inner(
                        id = '', 
                        type = '', 
                        attributes = test_coingecko_python.models.supported_networks_data_inner_attributes.SupportedNetworks_data_inner_attributes(
                            name = '', 
                            coingecko_asset_platform_id = '', ), )
                    ]
            )
        else:
            return SupportedNetworks(
        )
        """

    def testSupportedNetworks(self):
        """Test SupportedNetworks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
