# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from test_coingecko_python.api.networks_api import NetworksApi


class TestNetworksApi(unittest.TestCase):
    """NetworksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NetworksApi()

    def tearDown(self) -> None:
        pass

    def test_networks_list(self) -> None:
        """Test case for networks_list

        Supported Networks List
        """
        pass


if __name__ == '__main__':
    unittest.main()
