# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from test_coingecko_python.api.ping_api import PingApi


class TestPingApi(unittest.TestCase):
    """PingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PingApi()

    def tearDown(self) -> None:
        pass

    def test_api_usage(self) -> None:
        """Test case for api_usage

        Check API usage
        """
        pass


if __name__ == '__main__':
    unittest.main()
