openapi: 3.0.0
info:
  version: 3.1.0
  title: CoinGecko API
servers:
  - url: https://pro-api.coingecko.com/api/v3
  - url: https://api.coingecko.com/api/v3
security:
  - proKeyAuth: []
  - demoKeyAuth: []
paths:
  /key:
    get:
      tags:
        - Simple
      summary: Check API usage
      description: >-
        Check your API key usage
      operationId: api-usage
      responses:
        '200':
          description: API usage
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Key'
  /simple/supported_vs_currencies:
    get:
      tags:
        - Simple
      summary: Supported Currencies List
      description: >-
        Query all the supported currencies in CoinGecko API
      operationId: simple-supported-currencies
      responses:
        '200':
          description: List of supported currencies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportedCurrencies'
components:
  securitySchemes:
    proKeyAuth:
      type: apiKey
      in: header
      name: x-cg-pro-api-key
    demoKeyAuth:
      type: apiKey
      in: header
      name: x-cg-demo-api-key
  schemas:
    Key:
      type: object
      properties:
        plan:
          type: string
        rate_limit_request_per_minute:
          type: number
        monthly_call_credit:
          type: number
        current_total_monthly_calls:
          type: number
        current_remaining_monthly_calls:
          type: number
      example:
        plan: Other
        rate_limit_request_per_minute: 1000
        monthly_call_credit: 1000000
        current_total_monthly_calls: 0
        current_remaining_monthly_calls: 1000000
    SupportedCurrencies:
      type: array
      items:
        type: string
      example:
        - btc
        - eth
        - usd
