# coding: utf-8

# flake8: noqa
"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from test_coingecko_python.models.key import Key
from test_coingecko_python.models.supported_networks import SupportedNetworks
from test_coingecko_python.models.supported_networks_data_inner import SupportedNetworksDataInner
from test_coingecko_python.models.supported_networks_data_inner_attributes import SupportedNetworksDataInnerAttributes
