# coding: utf-8

# flake8: noqa

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from test_coingecko_python.api.networks_api import NetworksApi
from test_coingecko_python.api.ping_api import PingApi
from test_coingecko_python.api.simple_api import SimpleApi

# import ApiClient
from test_coingecko_python.api_response import ApiResponse
from test_coingecko_python.api_client import ApiClient
from test_coingecko_python.configuration import Configuration
from test_coingecko_python.exceptions import OpenApiException
from test_coingecko_python.exceptions import ApiTypeError
from test_coingecko_python.exceptions import ApiValueError
from test_coingecko_python.exceptions import ApiKeyError
from test_coingecko_python.exceptions import ApiAttributeError
from test_coingecko_python.exceptions import ApiException

# import models into sdk package
from test_coingecko_python.models.key import Key
from test_coingecko_python.models.supported_networks import SupportedNetworks
from test_coingecko_python.models.supported_networks_data_inner import SupportedNetworksDataInner
from test_coingecko_python.models.supported_networks_data_inner_attributes import SupportedNetworksDataInnerAttributes
